# CloudPress PHP Runner Worker (자동 생성)
name               = "cp-f5a7914b-wp-php"
main               = "php-runner.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CACHE"
id      = "815984231d4d4e37b7d80090a8437b9a"

[vars]
SITE_ID  = "f5a7914b-40d1-4901-bf67-330d62ba80d0"
GH_OWNER = "choichoi3227-crypto"
GH_REPO  = "cp-f5a7914b-site-f5a7914b"
