# CloudPress WordPress Worker 배포 설정 (자동 생성)
name               = "cp-f5a7914b-wp"
main               = "worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
# Worker URL: https://cp-f5a7914b-wp.choichoi3227.workers.dev

[[kv_namespaces]]
binding = "CACHE"
id      = "815984231d4d4e37b7d80090a8437b9a"

[[services]]
binding = "PHP_RUNNER"
service = "cp-f5a7914b-wp-php"

[vars]
SITE_ID      = "f5a7914b-40d1-4901-bf67-330d62ba80d0"
GH_OWNER     = "choichoi3227-crypto"
GH_REPO      = "cp-f5a7914b-site-f5a7914b"
GH_PAGES_URL = "https://choichoi3227-crypto.github.io/cp-f5a7914b-site-f5a7914b"
